### ISSUE TITLE
More tags for each place

### ISSUE THREAD

**Issue by Chng-Zhi-Xuan** [CS2103AUG2017-F09-B2/main#83]
**Enhancement**

As of V1.4, each place only has one tag. specifying whether it is a tourist attraction or a Michelin starred restaurant. We would like to introduce more tags to highlight the unique attribute each place provides.

**Example draft**
- Chicken_Rice
- Noodle
- Top_Visited_2016
- Newly_Opened

**Comment by huyuanrong** [comment]
Also maybe 
- Cuisine
- Nature/Shopping
- Indoor/Outdoor
